import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, Share2, Calendar, User, Tag, Terminal, Cpu } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Skill, BlogPost as BlogPostType } from '../types';
import { generateBlogPost, generateBlogImage } from '../services/geminiService';

interface BlogPostProps {
  skills: Skill[];
}

const BlogPost: React.FC<BlogPostProps> = ({ skills }) => {
  const { skillId } = useParams();
  const skill = skills.find(s => s.id === skillId);
  
  const [post, setPost] = useState<BlogPostType | null>(null);
  const [loadingStep, setLoadingStep] = useState<string>('');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchContent = async () => {
      if (!skill) return;
      
      // Reset state if we switch skills
      setPost(null);
      setError(null);

      try {
        setLoadingStep('AGENT: WRITER-01 > INITIALIZING CONTEXT...');
        await new Promise(r => setTimeout(r, 800)); // Cinematic delay

        setLoadingStep(`AGENT: WRITER-01 > ANALYZING SKILL: ${skill.name.toUpperCase()}...`);
        // Parallel generation for speed, but simulating sequential steps for UX
        const blogPromise = generateBlogPost(skill);
        
        setLoadingStep('AGENT: ARTIST-01 > REQUESTING VISUAL ASSETS (NANO BANANA)...');
        const imagePromise = generateBlogImage(skill.name, skill.category);

        const [blogData, imageUrl] = await Promise.all([blogPromise, imagePromise]);

        setLoadingStep('AGENT: CURATOR-01 > ASSEMBLING SEO METADATA...');
        await new Promise(r => setTimeout(r, 500));

        setPost({
          ...blogData,
          generatedImageUrl: imageUrl
        });

      } catch (err) {
        console.error(err);
        setError("Autonomous generation failed. Agents are offline.");
      } finally {
        setLoadingStep('');
      }
    };

    fetchContent();
  }, [skill]);

  if (!skill) {
    return <div className="text-center p-12 text-slate-500">Skill not found in registry.</div>;
  }

  if (loadingStep) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center p-8 space-y-6">
        <div className="w-16 h-16 relative">
             <div className="absolute inset-0 bg-blue-500/20 rounded-full animate-ping"></div>
             <div className="relative z-10 w-16 h-16 bg-slate-900 border border-blue-500/50 rounded-full flex items-center justify-center">
                <Cpu className="w-8 h-8 text-blue-400 animate-pulse" />
             </div>
        </div>
        <div className="font-mono text-sm text-blue-400 space-y-2 text-center">
            <p className="animate-pulse">{loadingStep}</p>
            <div className="h-1 w-64 bg-slate-900 rounded-full mx-auto overflow-hidden">
                <div className="h-full bg-blue-500 animate-progress-bar"></div>
            </div>
        </div>
      </div>
    );
  }

  if (error) {
     return <div className="text-center p-12 text-red-400 font-mono">{error}</div>;
  }

  return (
    <div className="max-w-5xl mx-auto animate-fade-in pb-12">
      <Link to="/" className="inline-flex items-center gap-2 text-slate-400 hover:text-white mb-6 transition-colors">
        <ArrowLeft className="w-4 h-4" /> Back to Registry
      </Link>

      {post && (
        <article className="grid grid-cols-1 lg:grid-cols-12 gap-12">
           {/* Main Content */}
           <div className="lg:col-span-8 space-y-8">
              <div className="space-y-4">
                  <div className="flex items-center gap-2 text-blue-400 font-mono text-xs tracking-wider uppercase">
                    <span className="bg-blue-900/30 px-2 py-1 rounded border border-blue-800">{skill.category}</span>
                    <span className="text-slate-500">|</span>
                    <span>{post.keywords[0]}</span>
                  </div>
                  <h1 className="text-4xl md:text-5xl font-bold text-slate-100 tracking-tight leading-tight">
                    {post.title}
                  </h1>
                  <div className="flex items-center gap-6 text-sm text-slate-400 border-b border-slate-800 pb-6">
                      <div className="flex items-center gap-2">
                          <User className="w-4 h-4 text-emerald-400" />
                          <span>Generated by {post.authorAgent}</span>
                      </div>
                      <div className="flex items-center gap-2">
                          <Calendar className="w-4 h-4" />
                          <span>{new Date(post.generatedDate).toLocaleDateString()}</span>
                      </div>
                  </div>
              </div>

              {post.generatedImageUrl && (
                  <div className="rounded-2xl overflow-hidden border border-slate-800 shadow-2xl relative group">
                      <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 to-transparent z-10"></div>
                      <img 
                        src={post.generatedImageUrl} 
                        alt={post.title}
                        className="w-full aspect-video object-cover transform group-hover:scale-105 transition-transform duration-700" 
                      />
                      <div className="absolute bottom-4 right-4 z-20 text-[10px] text-slate-400 font-mono bg-black/50 px-2 py-1 rounded backdrop-blur">
                          RENDERED BY NANO BANANA
                      </div>
                  </div>
              )}

              <div className="prose prose-invert prose-lg max-w-none text-slate-300 prose-headings:text-slate-100 prose-a:text-blue-400 prose-code:text-emerald-300 prose-code:bg-slate-900 prose-code:px-1 prose-code:rounded">
                 <ReactMarkdown>{post.content}</ReactMarkdown>
              </div>
           </div>

           {/* Sidebar */}
           <div className="lg:col-span-4 space-y-8">
              {/* Meta Card */}
              <div className="bg-slate-900/50 border border-slate-800 rounded-xl p-6 sticky top-8">
                  <h3 className="text-sm font-bold text-slate-100 uppercase mb-4 flex items-center gap-2">
                      <Terminal className="w-4 h-4 text-purple-400" />
                      Skill Metadata
                  </h3>
                  
                  <div className="space-y-4">
                      <div>
                          <div className="text-xs text-slate-500 font-mono mb-1">PROVIDER</div>
                          <div className="text-sm text-slate-200">{skill.provider}</div>
                      </div>
                      <div>
                          <div className="text-xs text-slate-500 font-mono mb-1">RISK SCORE</div>
                          <div className="flex items-center gap-2">
                              <div className="h-2 flex-1 bg-slate-800 rounded-full overflow-hidden">
                                  <div className="h-full bg-blue-500" style={{width: `${skill.riskScore}%`}}></div>
                              </div>
                              <span className="text-sm font-bold text-slate-200">{skill.riskScore}/100</span>
                          </div>
                      </div>
                      <div>
                          <div className="text-xs text-slate-500 font-mono mb-1">SEO KEYWORDS</div>
                          <div className="flex flex-wrap gap-2">
                              {post.keywords.map(k => (
                                  <span key={k} className="text-xs bg-slate-950 border border-slate-800 text-slate-400 px-2 py-1 rounded">#{k}</span>
                              ))}
                          </div>
                      </div>
                  </div>

                  <div className="mt-8 pt-6 border-t border-slate-800">
                      <h4 className="text-xs font-bold text-slate-500 uppercase mb-3">Jobs to be Done</h4>
                      <ul className="space-y-2">
                          {skill.outcomes.map((o, i) => (
                              <li key={i} className="flex items-start gap-2 text-sm text-slate-300">
                                  <span className="mt-1.5 w-1 h-1 bg-emerald-400 rounded-full"></span>
                                  {o}
                              </li>
                          ))}
                      </ul>
                  </div>
                  
                  <button className="w-full mt-6 bg-blue-600 hover:bg-blue-500 text-white font-medium py-3 rounded-lg transition-colors flex items-center justify-center gap-2">
                      <Share2 className="w-4 h-4" />
                      Share Analysis
                  </button>
              </div>
           </div>
        </article>
      )}
    </div>
  );
};

export default BlogPost;
